### ISSUE TITLE
Update tika-python dependency to latest available release

### ISSUE THREAD

**Issue by jjelosua** [Gradiant/FARO#9]

**Comment by hmightypirate** [comment]
Ok, integrated in the v1.0.2 branch

**Comment by jjelosua** [comment]
@hmightypirate We need to also change the jar download to use 1.22 instead of 1.21:

- https://github.com/Gradiant/FARO/blob/release/v1.0.2/faro/io_parser.py#L2
- https://github.com/Gradiant/FARO/blob/release/v1.0.2/faro_spider.sh#L10
- https://github.com/Gradiant/FARO/blob/release/v1.0.2/Dockerfile#L21

**Comment by hmightypirate** [comment]
Done
